global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus-server'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
    - targets: ['localhost:9100']

  - job_name: 'vm1'
    static_configs:
    - targets: ['localhost:9100']

  - job_name: 'vm2'
    static_configs:
    - targets: ['localhost:9100']
